config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "resturants#index"
  resources :resturants do
    resources :reviews, except: [:index, :show]
    collection do
      get 'search'
    end
  end


  match '/about_us', to: 'pages#about_us',      via: :get
  match '/contact_us', to: 'pages#contact_us',  via: :get

  #---#
  # match '/profile', to: 'users#show_profile',   via: :get
  resources :users do
    member do
    end

    collection do
      get 'profile', to: 'users#show_profile'
      get 'send_message'
      post 'send_to_reviewer'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :resturants
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	#belongs_to :user, required: false

end

app/models/resturant.rb
class Resturant < ActiveRecord::Base
  has_many :reviews
  belongs_to :category
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :address1
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zipcode
  validates_presence_of :phone

  validates_presence_of :price_range

  geocoded_by :full_address
  after_validation :geocode

  mount_uploader :image, ImageUploader

  def full_address
    [address1,address2,city,state,zipcode].join(', ')
  end

  def get_price_string
    @price_string = ""

    (1..price_range.to_i).each do |i|
      @price_string += "$"
    end

    # return price string:
    @price_string
  end

  #Search Form
  def self.search(params)
    resturants = Resturant.where(category_id: params[:category].to_i)
    resturants = resturants.where("name like ? or description like ?", "%#{params[:search]}%","%#{params[:search]}%") if params[:search].present?
    resturants = resturants.near(params[:location],20) if params[:location].present?
    resturants
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :resturant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  validates :email, presence: true, uniqueness: true

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :add_parameters_to_user, if: :devise_controller?

  def add_parameters_to_user
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	
	def new
		@favorites = Favorite.new
	end

	def index
	end

	#since there are no parameters other than the id of the
	#resturant u wanna add, the create method only gets that resturant ID
	def create 
		temp = Favorite.where(:fav_resturant_id => params[:fav_resturant_id], :user_id => params[:user_id])
		if temp.empty?
			@favorites = Favorite.new()
			@favorites.fav_resturant_id = params[:fav_resturant_id]
			@favorites.user_id = params[:user_id]

			if @favorites.save
				redirect_to Resturant.find(@favorites.fav_resturant_id.to_i), notice: "Successfully added to favorites"
			else
				flash[:danger] = "Couldn't add to favorites"
			end
		else
			redirect_to Resturant.find(temp.first.fav_resturant_id), notice: "This resturant is already in you favorites' list"
		end

	end

	def update
	end

	def show
	end

	def edit
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about_us
  end

  def contact_us
  end

end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
	before_action :authenticate_user!,only:[:create,:new]
	before_action :is_admin?, only: [:edit, :update, :destroy]

	def index
		visitor_latitude = 37.35138
		visitor_longitude = -121.850291
		#visitor_latitude = request.location.latitude
		#visitor_longitude = request.location.longitude
		@resturant = Resturant.near([visitor_latitude,visitor_longitude],20)
		#@resturants = Resturant.all
	end

	def new
		@resturant = Resturant.new
	end

	def create
		#check whether the restuarant is already in the database or not
		#only checking whether a restaurant with the phone exists or not
		@resturant = Resturant.new(resturant_params)
		if Resturant.where(:phone => @resturant.phone).exists?	
			#if it does, show this error and redirect to home page
			flash[:danger] = "This restaurant is already in the database"
			redirect_to new_resturant_path
		else
			#@resturant = Resturant.new(resturant_params)
			if @resturant.save
					redirect_to @resturant
			else
				flash[:danger] = @resturant.errors.full_messages.to_sentence
				render 'new'
			end
		end
	end

	def edit
		@resturant = Resturant.find(params[:id])
	end

	def update
		@resturant = Resturant.find(params[:id])
		@resturant.update(resturant_params)
		redirect_to @resturant
	end

	def destroy
		@resturant = Resturant.find(params[:id])
		@resturant.destroy
		redirect_to root_path
	end

	def show
		@resturant = Resturant.find(params[:id])
		@reviews = Review.where(resturant_id: @resturant)
		if @reviews.blank?
			@avg_rating = 0
		else
			@avg_rating = @reviews.average(:rating).round(2)
		end
	end

	def search
		@resturants = Resturant.search(params)
	end

	private
	def resturant_params
		params.require(:resturant).permit(:name,  :description, :category_id, :address1, :address2, :city,
																			:image, :state, :zipcode, :phone, :email, :price_range);
	end

	def is_admin?
		if !current_user.try(:admin?)
			flash[:danger] = "You are not authorized to edit or delete"
			redirect_to root_path
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_resturant
  before_action :authenticate_user!

  def new
    # check if user has already added a review for this restaurant:

    # NOTE: "begin"/"rescue" are like try/catch:
    begin
      # this first line throws an error if no review exists by this user for this restaurant (is therefore the user's first comment)
      # if an error is thrown, that means the user hasn't entered a comment yet, so let them add a comment (jump to "rescue"):
      @existing_review = Review.find_by_user_id_and_resturant_id(current_user.id, params[:resturant_id])

      # if continue, user has already added a comment before, so warn them that they can't add another comment:
      flash[:danger] = "You can only add 1 comment per restaurant. You already commented: \"" + @existing_review.comment + "\""
      redirect_to @resturant
    rescue
      # an error was thrown (user hasn't added a comment yet), so lest them add a comment:
      @review = Review.new(resturant: @resturant)
    end

  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.resturant = @resturant
    @review.save
    redirect_to @resturant
  end


  private

  def set_resturant
    @resturant = Resturant.find(params[:resturant_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show_profile
	  @my_review_resturant = Array.new
    @reviewer = User.find(params[:reviewer])
	  initialize_my_resturants(params[:reviewer])
	  render action: "profile"
  end

	def initialize_my_resturants(user_id)
		my_id = user_id.to_i
		@my_reviews = Review.where(:user_id => current_user.id)
		#@my_review_resturant = Resturant.where(:id => @my_reviews.resturant_id)
		@my_reviews.each do |rev|
			temp_res = Resturant.where(:id => rev.resturant_id)
			@my_review_resturant = @my_review_resturant + temp_res
		end
	end

	def add_to_favorites

  end

  def send_message
    @sender = current_user
    @receiver = User.find(params[:reviewer])

	end

	def send_to_reviewer
		UserMailer.message_to_reviewer(params[:sender], params[:receiver], params[:subject], params[:body]).deliver
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
The index

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navigationsBar/navigation'%>
    <!-- Starting of flash each do-->
    <div class = "container">
    <% flash.each do |key,value| %>
      <div class ="alert alert<%= key %>">
        <a href="#" data-dismiss="alert" class="close">x</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
      </div> <!-- Ending of flash each do-->
    <%end %>
    </div>
    <%= yield %>

  <script>
    $('.star-rating').raty({
        path: '/assets',
        readOnly: true,
        score: function (){
            return $(this).attr('data-score');
        }
    });
  </script>
  </body>
</html>

app/views/navigationsBar/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">-->
        <!--<img alt="Brand" id="logostyle" src="/assets/logo.png">-->
      <!--</a>-->
      <%= link_to image_tag("/assets/logo.png", :size=>"32"), root_path, class: "navbar-brand",id:"logo" %>
      <%= link_to "BestFinder", root_path, class: "navbar-brand",id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" class="navbar-form navbar-left">
        <li><%= link_to "View All Restaurants", resturants_path%></li>
        <li><a href="#">Link</a></li>
      </ul>



      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>
            <%= link_to "Sign up", new_user_registration_path %>
              &nbsp;&nbsp;
            <%= link_to "Sign in", new_user_session_path %>
        <% else %>
            <%= link_to "Edit Profile", edit_user_registration_path %>
            &nbsp &nbsp &nbsp
            <%= link_to "Sign out", destroy_user_session_path,method: :delete %>
            &nbsp &nbsp &nbsp
            <% @temp_user = current_user %>
            <%= link_to "Profile",  profile_path%>
        <%end%>

        
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More Information <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "About us", about_us_path%></li>
                <li><%= link_to "Contact us", contact_us_path%></li>
              </ul>
            </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/about_us.html.erb
<!DOCTYPE html> 
<html lang="en">
<head> 
<meta charset="UTF-8">

<title>About Us</title>

<link type="text/css" rel="stylesheet" href="/assets/about_us.css">
<link type="text/css" rel="stylesheet" href="../css/print.css" media="print">
</head> 
<body> 

<div id="wrapper"> 
<header> 

    <h1>About Us</h1>

</header>

<section id="leftcolumn">

<aside>


</aside>
</section>

<div id="brewsrightcolumn">
<div id="tablebackground">

<table summary="This table credits technical team">

<tr>
<h1>Yelppy Technical Team</h1>
  
</tr>
 

<tr>
  <th> <strong><h4>Product Mangager</h4></strong> </th>
  <td><img src="/assets/test_image.jpg" alt="Project Manager Pic" title="Maninderjit Singh"</td>

</tr>
<tr>
  <th><h4>Product Owner</h4></th>
  <td><img src="/assets/test_image.jpg" alt="Product Owner Pic" title="Su Pyae Tun" /></td>
  <td><img src="/assets/test_image.jpg" alt="Product Owner Pic" title="Kevin Tieu" /></td>
  
  
</tr>
<tr>
  <th><h4>Architect/Technical Lead</h4></th>
  <td><img src="/assets/test_image.jpg" alt="Architect Pic" title="Tim Davis" /></td>
  <td><img src="/assets/test_image.jpg" alt="Technical Lead Pic" title="Kevin Tieu" /></td>
  
</tr>
<tr>
  <th><h4>Software Developer</h4></th>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Tim Davis" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Maninderjit Singh" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Patrick Vu" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Yihua Li" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Myat Noe" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Dante Sanchez" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Kevin Tieu" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Developer Pic" title="Tao Liang" /></td>
  
</tr>

<tr>
  <th><h4>Software Tester</h4></th>
  <td><img src="/assets/test_image.jpg" alt="Software Tester Pic" title="Tim Davis" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Tester Pic" title="Patrick Vu" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Tester Pic" title="Myat Noe" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Tester Pic" title="Dante Sanchez" /></td>
  <td><img src="/assets/test_image.jpg" alt="Software Tester Pic" title="Tao Liang" /></td>
  
</tr>

<tr>
  <th><h4>Documentation</h4></th>
  <td><img src="/assets/test_image.jpg" alt="Documentor Pic" title="Maninderjit Singh" /></td>
  <td><img src="/assets/test_image.jpg" alt="Documentor Pic" title="Yihua Li" /></td>
  <td><img src="/assets/test_image.jpg" alt="Documentor Pic" title="Myat Noe" /></td>
  
</tr>
</table>
</div>




  
  
  
    
</div>

<footer>
<article id="stuff">
 
<strong>Company Statement</strong>  <br>  
We at best finder are committed to Blah Blah Blah... 

</article>
<a href="http://validator.w3.org/check?uri=referer">HTML checker</a> 
<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS checker</a>
<time datetime="20XX-XX-XX"> May 3, 2017</time>
</footer>


</div>

</body> 
</html>

app/views/pages/contact_us.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="/assets/contact_us.css">
<link type="text/css" rel="stylesheet" href="../css/print.css" media="print">
<title>Contact Us</title>
</head>

<body>

<div id="wrapper1"> 
<header> 

		<h1>Contact Us</h1>

</header>


<!--<section id="leftcolumn">

<nav>
<ul>
<li><a href="../Index.html">Home</a></li>

<li>Contact us</li>
</ul>

</nav>

</section>-->

<div id="rightcolumn">


<form id="gform" method="POST" action="https://script.google.com/macros/s/AKfycbzYMKZbJiVPbPCOMyBsTDosldMvzTlhjcDMFmRHTkqMz_76JhOW/exec">  



<form> 



<fieldset><legend>IDENTITY</legend>

<label for="first">First_Name: </label>
<input type="text" name="first" id="first" required placeholder="First"/><br>

<label for="last">Last_Name: </label>
<input type="text" name="last" id="last" required placeholder="Last"/><br>

<label for="email">Email: </label>
<input type="email" name="email" id="email" required placeholder="your.email@Xmail.com"/><br>

<label for="age">Age: </label>
<input type="text" name="age" id="age"/><br>

<label for="age">Phone_#: </label>
<input type="text" name="phone_number" id="phone_number"/><br>

</fieldset>


<fieldset><legend>ADDRESS</legend>
<label for="address"> Address: </label>
<input type="text" name="address" id="address"><br>

<label for="city">City: </label>
<input type="text" name="city" id="city"><br>

<label for="state">State: </label>
<input name="state" type="text" size="2" id="state"><br>

<label for="zip">ZIP: </label>
<input name="zip" type="text" id="zip"><br>
</fieldset>


<fieldset><legend>Favorite Food</legend><br>
<select name="beverage" multiple="multiple">
<option>American</option>
<option>Asian</option>
<option>Indian</option>
<option>Mexican</option>


</select><br>
Comments:
<br>
<textarea name="comments" cols="40" rows="5">Any Comments?</textarea>
<br>
<input type="submit" value="SUBMIT NOW!">
<input type="reset" value="REDUE!">

</form>
		
</div>

<footer>

<a href="http://validator.w3.org/check?uri=referer">HTML checker</a> 
<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS checker</a>

<time datetime="20XX-XX-XX"> May 3, 2017</time>
</footer>

</div>

<!-- Customise the Thankyou Message People See when they submit the form: -->
  <div style="display:none;" id="thankyou_message">
    <h2><em>Thanks</em> for contacting us!
      We will get back to you soon!</h2>
  </div>

  <!-- Submit the Form to Google Using "AJAX" -->
  <script data-cfasync="false" type="text/javascript"
  src="https://cdn.rawgit.com/dwyl/html-form-send-email-via-google-script-without-server/master/form-submission-handler.js"></script>
  <!-- <script data-cfasync="false" type="text/javascript"
  src="/form-submission-handler.js"></script> -->

</body>
</html>

app/views/resturants/_addnewresturant.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">

  </div>
</div>

app/views/resturants/_allcreateresturantlist.html.erb
<div class="container">

  <h2> Near By Restaurants </h2>

</div>
<div class ="container page-content">
  <div class="row">
    <% if @resturants.blank? %>
        <h3>Could not find a restaurant</h3>
    <%else%>
        <% @resturants.each do |resturant| %>
            <div class="col-md-4">
              <a class="overlay" href="resturant" title="resturant.name">
                <span class="more"></span>
                <% if resturant.image.url.present? %>
                    <%= link_to image_tag(resturant.image_url.to_s, :size=>"370x210"), resturant %>
                <% else %>
                    <%= link_to image_tag("http://placehold.it/370x210"), resturant %>
                <% end %>
              </a>
              <span class="prop-tag"></span>
              <div class="prop-info">
                <h3 class="prop-title"><%= link_to resturant.name, resturant %></h3>
                <ul class="more-info clearfix">
                  <li class="info-label clearfix"><span class="pull-left">Address:</span>
                    <span class="qty pull-right"><%= resturant.address1 %></span></li>
                </ul>
              </div><!-- prop-info ending point -->
            </div><!-- holder ending point -->
        <% end %>
    <% end %>
  </div><!-- row ending point -->
</div><!-- container ending point-->

app/views/resturants/_findnewresturant.html.erb
<div class=" center jumbotron">

  <div class="container">

    <div>
      <ul class="inline pull-left">
        <button type="button" class="btn btn-default navbar-btn" id="writeReviewbutton">
          <%= link_to "Create Resturant", new_resturant_path%></button>
      </ul>
      <ul class="inline pull-right">

      <% if !current_user %>
        <%= link_to "Sign up", new_user_registration_path %>
        &nbsp;&nbsp;
        <%= link_to "Sign in", new_user_session_path %>
      <% else %>
        <%= link_to "Edit Profile", edit_user_registration_path %>
        &nbsp &nbsp &nbsp
        <%= link_to "Sign out", destroy_user_session_path,method: :delete %>
	      &nbsp &nbsp &nbsp
	      <% @temp_user = current_user %>
        <%= link_to "Profile",  { controller: 'users', action: 'show_profile', reviewer: current_user.id } %>
      <%end%>
      </ul>
    </div>


    <h1> Find a restaurant </h1>


      <div id="locationfinder" class="col-lg-8 col-lg-offset-2">
        <center>
        <div class="search-form">
          <%= form_tag search_resturants_path, method: :get do |f| %>
              <%= text_field_tag :search,nil, placeholder: "pizza, bugers, etc" %>
              &nbsp&nbsp&nbsp
              <%= text_field_tag :location,nil, placeholder: "San Jose, San Francisco, etc" %>
              <br \><br \>
              <%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id]}) %>
              <br \><br \>
              <%= submit_tag 'Search', class: "btn span2 btn-realto-form btn-large" %>
          <% end %>
        </div><!-- /input-group -->
        </center>
      </div><!-- /.col-lg-6 -->



  </div>
</div>

app/views/resturants/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML,CSS,XML,JavaScript">
  <meta name="author" content="John Doe">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>This is Resturant Page</title>
</head>


<body>

<%= render 'resturants/findnewresturant'%>

<%= render 'resturants/allcreateresturantlist'%>

  <div class="container">
    <%= yield %>
  </div>

<script data-cfasync="false" type="text/javascript" src="https://cdn.rawgit.com/dwyl/html-form-send-email-via-google-script-without-server/master/form-submission-handler.js"></script>

</body>
</html>

app/views/resturants/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
</head>
<body>

<div class = "container">
  <div class ="row">
    <div class ='col-sm-6'>
      <div class="clearfix">
      <div class="clearfix padding30">

        <% if @resturant.image_url present? %>
        <%= image_tag(@resturant.image_url, :size=>"500x300") %>
        <% end %>

        <h2 class="prop-title pull-left margin0"><%=@resturant.name %>

        <% if current_user.try(:admin?) %>
        <small><%= link_to "Edit", edit_resturant_path, class: "btn btn-primary btn-mini"%></small>
        <small><%= link_to "Delete",resturant_path, method: :delete, data:
                {confirm: "Are you sure you want to delete?"}, class: "btn btn-danger btn-mini"%></small>
        <% else %>
        <% end %>

        </h2>
        <h2><span class="rating-value pull-right margin0 star-rating" data-score=<%= @avg_rating %>></span></h2>
      </div>

        <div class="clearfix padding030 row-fluid">

          <div class="descriptpart">
            <span class="pull-left">Description:</span>
            <br \>
            <span><%=@resturant.description%></span>
          </div>
          <br \>

          <div class="categorypart">
            <span class="pull-left">Category:</span>
            <span class="pull-right"><%=@resturant.category.name%></span>
          </div>
          <br \>
          <br \>
          <div class="addresspart">
            <span class="pull-left">Address:</span>
            <span class="pull-right"><%=@resturant.address1%></span>
          </div>
          <br \>
          <br \>

          <div class="citypart">
            <span class="pull-left">City:</span>
            <span class="pull-right"><%=@resturant.city%></span>
          </div>
          <br \>
          <br \>
          <div class="statepart">
            <span class="pull-left">State:</span>
            <span class="pull-right"><%=@resturant.state%></span>
          </div>
          <br \>
          <br \>
          <div class="zipcodepart">
            <span class="pull-left">Zipcode:</span>
            <span class="pull-right"><%=@resturant.zipcode%></span>
          </div>
          <br \>
          <br \>
          <div class="phonepart">
            <span class="pull-left">Phone:</span>
            <span class="pull-right"><%=@resturant.phone%></span>
          </div>

        </div>
        <div>
        </div>
      </div>
    </div>

    <!-- Google Map API -->
    <div class ='col-sm-6 align-items-end'>



      <div id="googleMap" style="width:100%;height:350px;"></div>
      <script>
          function myMap() {
              var mapProp= {
                  center:new google.maps.LatLng(<%=@resturant.latitude %>,<%=@resturant.longitude %>),
                  zoom:16,
              };
              var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

              var myLatLng = {lat: <%=@resturant.latitude %>, lng: <%=@resturant.longitude %>};
              var marker = new google.maps.Marker({
                  position: myLatLng,
                  map: map,
                  title: 'Hello World!'
              });
          }
      </script>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDe5ktgOVa6Q2AF8J6xp0lIrkRaPmDBC2w&callback=myMap"></script>

      <!--
      To use this code on your website, get a free API key from Google.
      Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
      -->
    </div>
    <!-- Ending of Google API-->
  </div>
</div>

<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">

      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/assets/system.jpeg" alt="Chania" width="460" height="345">
      </div>

      <div class="item">
        <img src="/assets/sys.jpeg" alt="Chania" width="460" height="345">
      </div>

      <div class="item">
        <img src="/assets/sys.jpeg" alt="Flower" width="460" height="345">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class ="container">
  <div class="reviewSession">
    <div>
      <br />
      <button><%= link_to "Review", new_resturant_review_path(@resturant)%></button>
      <br />
      <h2>Review</h2>
      </div>
      <% if @reviews.blank? %>
        <p>No Reviews Yet!</p>
      <% else %>
        <table class="table">

          <thead>
            <tr>
              <th class="col-mid-3"></th>
              <th class="col-mid-9"></th>
            </tr>
          </thead>

          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td>
                  <h5><%= link_to "#{review.user.first_name} #{review.user.last_name}",  { controller: 'users', action: 'show_profile', reviewer: review&.user&.id } %></h5>
                </td>
                <td>
                  <div class="clearfix star-rating" data-score=<%= review.rating %>></div>
                  <%= review.comment %>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
      <% end %>
    <br />
  </div>
</div>

</body>
</html>

app/views/reviews/new.html.erb
<%= form_for [@resturant, @review] do |f| %>
  <%= f.text_area :comment %>
  <%= f.number_field :rating, value: 1, min: 1, max: 5 %>
  <%= f.submit %>
<%end %>

app/views/reviews/show.html.erb
This is show review page